---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: devspaces-og
  namespace: {{ $.Values.devSpaces.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  upgradeStrategy: Default